name: video_viewer
description: Minimalist video viewer with spectacular user experience.
version: 1.0.0
homepage: https://github.com/seel-channel/video_viewer

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  helpers: ^1.0.1
  video_player: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
